### ISSUE TITLE
D3D9: Picture is very bright, FPS is very poor

### ISSUE THREAD

**Issue by mick-p1982** [microsoft/D3D12TranslationLayer#48]
I was really hoping I could use this to interop with OpenXR (I'd been doing an OpenGL port with ANGLE for weeks when I stumbled across this on Wikipedia's WDDM page) except for some reason it's making my game app very bright (bright white colors) and the frame rate is very low, I can't say how low because I'm on a new PC with D3D12 that should run the app with frame rate to spare several times over, however D3D9on12 is running well below 60fps (the average is on lower side of 30-60fps with 60hz syncing.)

TEST RESULTS: For the record, with "vsync" disabled, plain D3D9 runs about 145fps and D3D9on12 runs about 45fps in this case.

EDITED: I should add I'm using the Windows SDK version of d3d9.dll, on up-to-date "fast ring" "insiders build" of Windows 10.

**Comment by jenatali** [comment]
You probably want to file this on D3D9On12's repository instead: https://github.com/microsoft/D3D9On12.

**Comment by mick-p1982** [comment]
I guess so. It has 0 issues, opened or closed. I swear I've been bouncing around multiple Github projects for this topic and I'm not I'd even heard of that one yet :) I see the same group there, and the project description here appears to cover D3D9on12 as well.

**Comment by jenatali** [comment]
That repository was published 2 weeks ago. This repository is the host of a bunch of shared code between D3D11On12 and D3D9On12 (plus OpenCLOn12), and could also be used directly by apps.
