### ISSUE TITLE
Lacking documentation on 9on12 Interop API

### ISSUE THREAD

**Issue by AmazingTurtle** [microsoft/D3D12TranslationLayer#8]
I'm trying to get my hands on 9On12 but I can't seem to find any good source of documentation besides [your recent blogpost](https://devblogs.microsoft.com/directx/coming-to-directx-12-d3d9on12-and-d3d11on12-resource-interop-apis/).

I'm running on 19041.208 (insider slow ring). In a `v140` project I'm using the `10.0.19041.0` target version. I got the header files but I can not link the `Direct3DCreate9On12` function (`LNK2001`). Do I need to specify something in order to make that work? For now I'm working around this issue with a dynamic call as [shown here](https://github.com/Joshua-Ashton/neun-auf-zwoelf/blob/3037a6db80c863c814641e6666c508abdab98b46/d3d9.cpp).

Also...
```
    D3D9ON12_ARGS arg = {};
    arg.Enable9On12 = true;
    m_pD3D = RunD3D9Proc<decltype(Direct3DCreate9On12)>("Direct3DCreate9On12", D3D_SDK_VERSION, &arg, 1);
```

the code above succeeds and the device is created and everything works fine BUT...
Querying the interface for IDirect3dDevice9On12 fails with `E_NOINTERFACE`. Why is that?

```
    IDirect3DDevice9On12* mpD3D12 = NULL;
    hr = m_pD3D->QueryInterface(__uuidof(IDirect3DDevice9On12), (void**)&mpD3D12);
```

I would look up how to solve this myself but I just can't find any good resource on this.

**Comment by jenatali** [comment]
That all looks right, except you have to `CreateDevice()` before the `QueryInterface` will work. I don't think those exports are in `d3d9.lib` and we should probably fix that.

**Comment by AmazingTurtle** [comment]
Thank you for your quick reply @jenatali. I missed that I had to call QueryInterface on the device... It's working now.

```
...
    hr = m_pD3D->CreateDevice(AdapterToUse, pDeviceInfo->DeviceType, m_hWndFocus, pModeInfo->dwBehavior | D3DCREATE_MULTITHREADED, &m_d3dpp, &m_pd3dDevice);

    if( SUCCEEDED(hr) )
    {

        IDirect3DDevice9On12* mpD3D12 = NULL;
        hr = m_pd3dDevice->QueryInterface(__uuidof(IDirect3DDevice9On12), (void**)&mpD3D12);
...
```
