### ISSUE TITLE
Missing d3d9.lib exports

### ISSUE THREAD

**Issue by AmazingTurtle** [microsoft/D3D12TranslationLayer#9]
As described [here](https://github.com/microsoft/D3D12TranslationLayer/issues/8#issuecomment-625900663), `d3d9.lib` exports for `Direct3DCreate9On12` and others are missing.

I can confirm this issue on windows version `19041.208` (insider slow ring) on a `v140` project using the `10.0.19041.0` target SDK version.

The exports exist in the `d3d9.dll` however and calling those functions can be achieved with [a hack](https://github.com/Joshua-Ashton/neun-auf-zwoelf/blob/3037a6db80c863c814641e6666c508abdab98b46/d3d9.cpp) - basically using GetProcAddress to retrieve the exported function and calling it.

**Comment by jenatali** [comment]
(Sorry for not responding for so long...)

I don't see this. I see `Direct3DCreate9On12` exported from `d3d9.lib` in the 10.0.19041.0 SDK, confirmed with `link.exe /dump /headers "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64\d3d9.lib"`:

```
  Version      : 0
  Machine      : 8664 (x64)
  TimeDateStamp: F5D00EF8
  SizeOfData   : 0000001D
  DLL name     : d3d9.dll
  Symbol name  : Direct3DCreate9On12
  Type         : code
  Name type    : ordinal
  Ordinal      : 20
```
